//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18052
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez le projet Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Intercamber {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Intercamber() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Intercamber", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Admin.
        /// </summary>
        internal static string Admin_PageName {
            get {
                return ResourceManager.GetString("Admin_PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Agenda.
        /// </summary>
        internal static string Agenda_PageName {
            get {
                return ResourceManager.GetString("Agenda_PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Intercambers.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Help.
        /// </summary>
        internal static string Assistance_PageName {
            get {
                return ResourceManager.GetString("Assistance_PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My discussions.
        /// </summary>
        internal static string ChatList_PageName {
            get {
                return ResourceManager.GetString("ChatList_PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Discussions.
        /// </summary>
        internal static string Chat_PageName {
            get {
                return ResourceManager.GetString("Chat_PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connected.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My contacts.
        /// </summary>
        internal static string Contacts_PageName {
            get {
                return ResourceManager.GetString("Contacts_PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Argentina.
        /// </summary>
        internal static string Countries_ag {
            get {
                return ResourceManager.GetString("Countries_ag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Belgium.
        /// </summary>
        internal static string Countries_be {
            get {
                return ResourceManager.GetString("Countries_be", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Germany.
        /// </summary>
        internal static string Countries_de {
            get {
                return ResourceManager.GetString("Countries_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à France.
        /// </summary>
        internal static string Countries_fr {
            get {
                return ResourceManager.GetString("Countries_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Grece.
        /// </summary>
        internal static string Countries_gr {
            get {
                return ResourceManager.GetString("Countries_gr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Italy.
        /// </summary>
        internal static string Countries_it {
            get {
                return ResourceManager.GetString("Countries_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Spain.
        /// </summary>
        internal static string Countries_sp {
            get {
                return ResourceManager.GetString("Countries_sp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à United Kingdom.
        /// </summary>
        internal static string Countries_uk {
            get {
                return ResourceManager.GetString("Countries_uk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à United States of America.
        /// </summary>
        internal static string Countries_us {
            get {
                return ResourceManager.GetString("Countries_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disconnected.
        /// </summary>
        internal static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Talking with .
        /// </summary>
        internal static string Discussion_TalkWith {
            get {
                return ResourceManager.GetString("Discussion_TalkWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Establishment management.
        /// </summary>
        internal static string EstablishmentAdmin_PageName {
            get {
                return ResourceManager.GetString("EstablishmentAdmin_PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My contacts.
        /// </summary>
        internal static string Home_MyContacts {
            get {
                return ResourceManager.GetString("Home_MyContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home.
        /// </summary>
        internal static string Home_PageName {
            get {
                return ResourceManager.GetString("Home_PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à german.
        /// </summary>
        internal static string Languages_de {
            get {
                return ResourceManager.GetString("Languages_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à english.
        /// </summary>
        internal static string Languages_en {
            get {
                return ResourceManager.GetString("Languages_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à french.
        /// </summary>
        internal static string Languages_fr {
            get {
                return ResourceManager.GetString("Languages_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à spanish.
        /// </summary>
        internal static string Languages_sp {
            get {
                return ResourceManager.GetString("Languages_sp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have no new messages.
        /// </summary>
        internal static string LeftBar_0NewMessages {
            get {
                return ResourceManager.GetString("LeftBar_0NewMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contacts requests.
        /// </summary>
        internal static string LeftBar_ContactRequests {
            get {
                return ResourceManager.GetString("LeftBar_ContactRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Time cumulated in {0}.
        /// </summary>
        internal static string LeftBar_CumulatedIn {
            get {
                return ResourceManager.GetString("LeftBar_CumulatedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Currently learning {0}.
        /// </summary>
        internal static string LeftBar_Learning {
            get {
                return ResourceManager.GetString("LeftBar_Learning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My discussions.
        /// </summary>
        internal static string LeftBar_MyDiscussions {
            get {
                return ResourceManager.GetString("LeftBar_MyDiscussions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My penpals.
        /// </summary>
        internal static string LeftBar_MyPenpals {
            get {
                return ResourceManager.GetString("LeftBar_MyPenpals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My profile.
        /// </summary>
        internal static string LeftBar_MyProfile {
            get {
                return ResourceManager.GetString("LeftBar_MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have {0} contact requests.
        /// </summary>
        internal static string LeftBar_NContactRequests {
            get {
                return ResourceManager.GetString("LeftBar_NContactRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have {0} new messages.
        /// </summary>
        internal static string LeftBar_NNewMessages {
            get {
                return ResourceManager.GetString("LeftBar_NNewMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I am fluent in {0}.
        /// </summary>
        internal static string LeftBar_Speaking {
            get {
                return ResourceManager.GetString("LeftBar_Speaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à points.
        /// </summary>
        internal static string LeftBar_TimeUnit {
            get {
                return ResourceManager.GetString("LeftBar_TimeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login or password incorrect.
        /// </summary>
        internal static string Login_BadLoginOrPassword {
            get {
                return ResourceManager.GetString("Login_BadLoginOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connect.
        /// </summary>
        internal static string Login_Connect {
            get {
                return ResourceManager.GetString("Login_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connect to Intercambers.
        /// </summary>
        internal static string Login_ConnectTitle {
            get {
                return ResourceManager.GetString("Login_ConnectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        internal static string Login_Email {
            get {
                return ResourceManager.GetString("Login_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forgotten password?.
        /// </summary>
        internal static string Login_ForgottenPassword {
            get {
                return ResourceManager.GetString("Login_ForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        internal static string Login_PageName {
            get {
                return ResourceManager.GetString("Login_PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        internal static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log out.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Moderation.
        /// </summary>
        internal static string Moderate_PageName {
            get {
                return ResourceManager.GetString("Moderate_PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My penpals.
        /// </summary>
        internal static string MyPenpals_MyPenpals {
            get {
                return ResourceManager.GetString("MyPenpals_MyPenpals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My contact requests.
        /// </summary>
        internal static string MyPenpals_PendingRequests {
            get {
                return ResourceManager.GetString("MyPenpals_PendingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Online users: {0}.
        /// </summary>
        internal static string NumberOnlineUsers {
            get {
                return ResourceManager.GetString("NumberOnlineUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My profile.
        /// </summary>
        internal static string Profil_PageName {
            get {
                return ResourceManager.GetString("Profil_PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Project.
        /// </summary>
        internal static string Project_PageName {
            get {
                return ResourceManager.GetString("Project_PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reporting.
        /// </summary>
        internal static string Reporting_PageName {
            get {
                return ResourceManager.GetString("Reporting_PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        internal static string SearchContacts_ColAdd {
            get {
                return ResourceManager.GetString("SearchContacts_ColAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Age.
        /// </summary>
        internal static string SearchContacts_ColAge {
            get {
                return ResourceManager.GetString("SearchContacts_ColAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connected.
        /// </summary>
        internal static string SearchContacts_ColConnected {
            get {
                return ResourceManager.GetString("SearchContacts_ColConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Location.
        /// </summary>
        internal static string SearchContacts_ColLocation {
            get {
                return ResourceManager.GetString("SearchContacts_ColLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        internal static string SearchContacts_ColName {
            get {
                return ResourceManager.GetString("SearchContacts_ColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You are looking for a penpal ?.
        /// </summary>
        internal static string SearchContacts_LookingForPenpal {
            get {
                return ResourceManager.GetString("SearchContacts_LookingForPenpal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search contacts.
        /// </summary>
        internal static string SearchContacts_PageName {
            get {
                return ResourceManager.GetString("SearchContacts_PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Here are the penpals Intercambers recommand you.
        /// </summary>
        internal static string SearchContacts_ProposedPenpals {
            get {
                return ResourceManager.GetString("SearchContacts_ProposedPenpals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error: could not send request.
        /// </summary>
        internal static string SearchContacts_RequestSentError {
            get {
                return ResourceManager.GetString("SearchContacts_RequestSentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contact request has been sent to .
        /// </summary>
        internal static string SearchContacts_RequestSentTo {
            get {
                return ResourceManager.GetString("SearchContacts_RequestSentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find a penpal living in .
        /// </summary>
        internal static string SearchContacts_SelectContactCountry {
            get {
                return ResourceManager.GetString("SearchContacts_SelectContactCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find a penpal with the following hobbies.
        /// </summary>
        internal static string SearchContacts_SelectContactHobbies {
            get {
                return ResourceManager.GetString("SearchContacts_SelectContactHobbies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à who is fluent in .
        /// </summary>
        internal static string SearchContacts_SelectContactLanguage {
            get {
                return ResourceManager.GetString("SearchContacts_SelectContactLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send request.
        /// </summary>
        internal static string SearchContacts_SendRequest {
            get {
                return ResourceManager.GetString("SearchContacts_SendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send contact request to .
        /// </summary>
        internal static string SearchContacts_SendRequestTo {
            get {
                return ResourceManager.GetString("SearchContacts_SendRequestTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search a penpal.
        /// </summary>
        internal static string SearchContacts_Step1 {
            get {
                return ResourceManager.GetString("SearchContacts_Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Customize request.
        /// </summary>
        internal static string SearchContacts_Step2 {
            get {
                return ResourceManager.GetString("SearchContacts_Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find your penpal.
        /// </summary>
        internal static string SearchContacts_Step3 {
            get {
                return ResourceManager.GetString("SearchContacts_Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your message.
        /// </summary>
        internal static string SearchContacts_YourMessage {
            get {
                return ResourceManager.GetString("SearchContacts_YourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toolbox.
        /// </summary>
        internal static string Toolbox_PageName {
            get {
                return ResourceManager.GetString("Toolbox_PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User management.
        /// </summary>
        internal static string UserAdmin_PageName {
            get {
                return ResourceManager.GetString("UserAdmin_PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validate.
        /// </summary>
        internal static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vocabulary.
        /// </summary>
        internal static string Vocabulary_PageName {
            get {
                return ResourceManager.GetString("Vocabulary_PageName", resourceCulture);
            }
        }
    }
}
