//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CML.Intercamber.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class Countries
    {
        public Countries()
        {
            this.Users = new HashSet<Users>();
            this.Languages = new HashSet<Languages>();
        }
    
        public string IdCountry { get; set; }
        public bool Enabled { get; set; }
    
        public virtual ICollection<Users> Users { get; set; }
        public virtual ICollection<Languages> Languages { get; set; }
    }
}
