//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CML.Intercamber.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hobbies
    {
        public long IdHobby { get; set; }
        public string LblHobby { get; set; }
        public int OrderHobby { get; set; }
        public Nullable<long> IdHobbyParent { get; set; }
    }
}
