//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CML.Intercamber.Business
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IntercamberEntities : DbContext
    {
        public IntercamberEntities()
            : base("name=IntercamberEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ContactRequests> ContactRequests { get; set; }
        public DbSet<Contacts> Contacts { get; set; }
        public DbSet<Countries> Countries { get; set; }
        public DbSet<Establishments> Establishments { get; set; }
        public DbSet<Languages> Languages { get; set; }
        public DbSet<Profils> Profils { get; set; }
        public DbSet<ThreadMessages> ThreadMessages { get; set; }
        public DbSet<Threads> Threads { get; set; }
        public DbSet<ThreadUsers> ThreadUsers { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<UsersLearnLanguages> UsersLearnLanguages { get; set; }
        public DbSet<UsersSpokenLanguages> UsersSpokenLanguages { get; set; }
    }
}
