//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CML.Intercamber.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class Threads
    {
        public Threads()
        {
            this.ThreadMessages = new HashSet<ThreadMessages>();
            this.ThreadUsers = new HashSet<ThreadUsers>();
        }
    
        public long IdThread { get; set; }
        public int IdTypeThread { get; set; }
        public System.DateTime DateCreate { get; set; }
    
        public virtual ICollection<ThreadMessages> ThreadMessages { get; set; }
        public virtual ICollection<ThreadUsers> ThreadUsers { get; set; }
    }
}
