//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CML.Intercamber.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThreadMessages
    {
        public long IdMessage { get; set; }
        public long IdThread { get; set; }
        public long IdUser { get; set; }
        public System.DateTime DateMessage { get; set; }
        public string Message { get; set; }
        public string MessageCorrection { get; set; }
    
        public virtual Threads Threads { get; set; }
    }
}
