//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CML.Intercamber.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersLearnLanguages
    {
        public long IdUser { get; set; }
        public string IdLanguage { get; set; }
        public string LanguageLevel { get; set; }
    
        public virtual Languages Languages { get; set; }
        public virtual Users Users { get; set; }
    }
}
