//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CML.Intercamber.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.ContactRequests = new HashSet<ContactRequests>();
            this.ContactRequests1 = new HashSet<ContactRequests>();
            this.Contacts = new HashSet<Contacts>();
            this.Contacts1 = new HashSet<Contacts>();
            this.ThreadUsers = new HashSet<ThreadUsers>();
            this.UsersLearnLanguages = new HashSet<UsersLearnLanguages>();
            this.UsersSpokenLanguages = new HashSet<UsersSpokenLanguages>();
        }
    
        public long IdUser { get; set; }
        public Nullable<int> IdProfil { get; set; }
        public Nullable<int> IdEstablishment { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public bool MustChangePassword { get; set; }
        public Nullable<int> IdGender { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public bool Enabled { get; set; }
        public System.DateTime DateCreate { get; set; }
        public string IdCountry { get; set; }
        public string City { get; set; }
    
        public virtual ICollection<ContactRequests> ContactRequests { get; set; }
        public virtual ICollection<ContactRequests> ContactRequests1 { get; set; }
        public virtual ICollection<Contacts> Contacts { get; set; }
        public virtual ICollection<Contacts> Contacts1 { get; set; }
        public virtual Countries Countries { get; set; }
        public virtual ICollection<ThreadUsers> ThreadUsers { get; set; }
        public virtual ICollection<UsersLearnLanguages> UsersLearnLanguages { get; set; }
        public virtual ICollection<UsersSpokenLanguages> UsersSpokenLanguages { get; set; }
    }
}
